name: Setup pipeline and test

on:
  workflow_dispatch:
  
  push:
    branches:
    - main
    paths:
    - project/**
    - .github/workflows/**

jobs:
  setup-pipeline-and-test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    # Install python
    - name: Set up Python 3.11
      uses: actions/setup-python@v4
      with:
        python-version: 3.11
  # Run pipeline
    - name: Run pipeline
      run: ls -la

    # Run pipeline
    - name: Run pipeline
      run: |
        ./project/pipeline.sh

      # For debugging purposes (logging)
    - name: Run pipeline2
      run: ls -la

      # For debugging purposes (logging) 
    - name: Run pipeline
      run: ls ./project

    # Run tests
    - name: Run tests
      run: |
        ./project/tests.sh
