name: Exercise Feedback 2

on:
  push:
    branches:
    - main
    paths:
    - project/**

jobs:
  exercise-feedback:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        path: main

    # Install python
    - name: Set up Python 3.11
      uses: actions/setup-python@v4
      with:
        python-version: 3.11

    # Run pipeline
    - name: Run pipeline
      run: |
        ./project/pipeline.sh

    # Run pipeline
    - name: Run tests
      run: |
        ./project/tests.sh
